version: 0.2

phases:
  install:
    commands:
      - echo Logging in to Docker Hub...
      - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

  pre_build:
    commands:
      - echo Starting pre-build phase...
      - echo Setting environment variables...
      - IMAGE_NAME=users-microservices
      - IMAGE_TAG=latest # Tag the image with a timestamp
      - mvn clean package
      - mkdir -p target
      - echo Sample file > target/example.txt
      - echo Verifying build context...
      - ls -l
      - ls -l ./target
      - echo current directory
      - pwd
      - echo Pre-build phase complete.

  build:
    commands:
      - echo Starting build phase...
      - echo Building Docker image...
      - docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG} .
      - echo Build phase complete.

  post_build:
    commands:
      - echo Starting post-build phase...
      - echo Pushing Docker image to Docker Hub...
      - docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
      - echo Docker image pushed successfully.
      - echo Post-build phase complete.
      - echo Generating imagedefinitions.json...
      - echo '[{"name":"users-microservices-mohit-hub","imageUri":"'${DOCKERHUB_USERNAME}'/'${IMAGE_NAME}':'${IMAGE_TAG}'"}]' > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files: imagedefinitions.json
 
