version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Logging in to Docker Hub...
      - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

  pre_build:
    commands:
      - echo Starting pre-build phase...
      - echo Setting environment variables...
      - IMAGE_NAME=users-microservices
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S) # Tag the image with a timestamp
      - echo Pre-build phase complete.

  build:
    commands:
      - echo Starting build phase...
      - echo Building Docker image...
      - docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG} .
      - echo Build phase complete.

  post_build:
    commands:
      - echo Starting post-build phase...
      - echo Pushing Docker image to Docker Hub...
      - docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
      - echo Docker image pushed successfully.
      - echo Post-build phase complete.
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_NAME $DOCKERHUB_USERNAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
